QuanLy_TourDuLich/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Routing;

using QuanLy_TourDuLich.Models;

namespace QuanLy_TourDuLich.Areas.Admin.Controllers
{
    public class HomeAdminController : Controller
    {
        // GET: Admin/HomeAdmin
        CSDL_QLTourDataContext data = new CSDL_QLTourDataContext();
        public ActionResult Index()
        {
            List<Tour> dsTour = data.Tours.ToList();

            return View(dsTour);

        }
        public ActionResult ThemMoiTour()
        {
            ViewBag.LoaiTour = new SelectList(data.Loai_Tours.ToList().OrderBy(t => t.id), "id", "Name");
            return View(new Tour());
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoiTour(Tour model)
        {
            if (ModelState.IsValid)
            {
                data.Tours.InsertOnSubmit(model);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return View(model) ;
        }
        public ActionResult ThemHinhAnhTour(int id)
        {
            return View(id);
        }
        [HttpPost]
        public ActionResult ThemHinhAnhTour(int id, IEnumerable<HttpPostedFileBase> fileUpLoad) 
            //Thêm hình ảnh cho tour có tour_id == id
        {
            var t = data.Tours.FirstOrDefault(a => a.id == id);
            if (fileUpLoad == null || !fileUpLoad.Any() || fileUpLoad.All(f => f == null))
            {
                ViewBag.Thongbao = "Vui lòng chọn ít nhất 1 ảnh";
                return View(t);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    // Duyệt qua các tệp ảnh được tải lên và lưu trữ chúng
                    foreach (var file in fileUpLoad)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            var path = Path.Combine(Server.MapPath("~/img"), fileName);

                            // Kiểm tra xem tệp đã tồn tại chưa, nếu chưa thì lưu trữ tệp
                            if (!System.IO.File.Exists(path))
                            {
                                file.SaveAs(path);
                                data.Image_Tours.InsertOnSubmit(new Image_Tour
                                {
                                    Tour_id = t.id,
                                    Name = fileName
                                });
                            }
                            else
                            {
                                ViewBag.Thongbao = "Một hoặc nhiều hình ảnh đã tồn tại";
                                return View(t);
                            }
                        }
                    }
                    data.SubmitChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(t);
        }

        public ActionResult ChiTietTour(int id) // Hiển thị chi tiết tour
        {
            return View(data.Tours.FirstOrDefault(t => t.id == id));
        }

        public ActionResult dsAnh(int id) //Lấy ra List hình ảnh của tour có Tour_id == id
        {
            return PartialView(data.Image_Tours.Where(t => t.Tour_id == id).ToList());
        }

        //Xóa 1 tour
       public ActionResult XoaTour(int id)
        {
            var t = data.Tours.FirstOrDefault(a => a.id == id);
            var image = t.Image_Tours.ToList();
            //xóa ảnh trước khi xóa tour
            if (image != null)
            {
                foreach(var item in image)
                {
                    var imagePath = Path.Combine(Server.MapPath("~/img"), item.Name);

                    // Delete the file from the file system
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }

                    // Delete the record from the database
                    data.Image_Tours.DeleteOnSubmit(item);
                }
                
            }
            data.Tours.DeleteOnSubmit(t);
            data.SubmitChanges();
            return RedirectToAction("Index");

        }

        //Edit tour
        public ActionResult Edit(int id)
        {
            ViewBag.LoaiTour = new SelectList(data.Loai_Tours.ToList().OrderBy(t => t.id), "id", "Name");
            return View(data.Tours.FirstOrDefault(t=>t.id==id));
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Tour model)
        {
            if (ModelState.IsValid)
            {
                var tour = data.Tours.FirstOrDefault(t => t.id == model.id);
                if (tour != null)
                {
                    tour.Name = model.Name;
                    tour.Gia = model.Gia;
                    tour.MoTa = model.MoTa;
                    tour.LichTrinh = model.LichTrinh;
                    tour.DiemKhoiHanh = model.DiemKhoiHanh;
                    tour.NgayKetThuc = model.NgayKetThuc;
                    tour.SoLuongCon = model.SoLuongCon;
                    tour.Loai_Tour_id = model.Loai_Tour_id;
                    tour.NgayKhoiHanh = model.NgayKhoiHanh;
                    tour.DiemDen = model.DiemDen;
                    tour.Loai_Tour_id = model.Loai_Tour_id;
                    data.SubmitChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.LoaiTour = new SelectList(data.Loai_Tours.ToList().OrderBy(t => t.id), "id", "Name");

            return View("model");
        }

        
        public ActionResult XoaHinhAnh(int id)
        {
            return View(data.Image_Tours.Where(t => t.Tour_id == id).ToList());
        }
        [HttpPost]
        public ActionResult XoaHinhAnh(int imageId, int tourId)
        {
            var image = data.Image_Tours.FirstOrDefault(i => i.id == imageId);
            if (image != null)
            {
                var imagePath = Path.Combine(Server.MapPath("~/img"), image.Name);

                // Delete the file from the file system
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }

                // Delete the record from the database
                data.Image_Tours.DeleteOnSubmit(image);
                data.SubmitChanges();
            }

            return RedirectToAction("XoaHinhAnh",new { id = tourId });
        }

        public ActionResult danhSachDatTour()
        {
            var lst = data.DatTours.ToList();
            return View(lst);
        }

        public ActionResult XacNhanDDH(int id)
        {
            DatTour ddh = data.DatTours.FirstOrDefault(t => t.id == id);
            ddh.id_TrangThai = 2;
            data.SubmitChanges();
            return RedirectToAction("danhSachDatTour");
        }

        public ActionResult HuyDDH(int id)
        {
            DatTour ddh = data.DatTours.FirstOrDefault(t => t.id == id);
            ddh.id_TrangThai = 5;
            data.SubmitChanges();
            return RedirectToAction("danhSachDatTour");
        }

        public ActionResult ChiTietDatTour(int id)
        {
            List<ChiTiet_DatTour> ctdt = data.ChiTiet_DatTours.Where(t => t.DatTour_id == id).ToList();
            ViewBag.MaDT = id;
            return View(ctdt);
        }


       
    }
}

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/AnhChoCard.cshtml
@model List<QuanLy_TourDuLich.Models.Image_Tour>

@foreach (var item in Model)
{
    <img src="~/img/@item.Name"  class="card-img-top" />
}

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/ChiTietDatTour.cshtml
@model List<QuanLy_TourDuLich.Models.ChiTiet_DatTour>
@{
    ViewBag.Title = "ChiTietDatTour";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<b style="font-size:45px; color:black">Chi tiết đặt tour</b>
<strong>Mã đặt tour: @ViewBag.Madt</strong>
<table class="table table-bordered">
    <tr>
        <th>Mã tour</th>
        <th>Tên Tour</th>
        <th>Điểm xuất phát</th>
        <th>Ngày khởi hành</th>
        <th>Ngày kết thúc</th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Tour_id</td>
                    <td>@item.Tour.Name</td>
                    <td>@item.Tour.DiemKhoiHanh</td>
                    <td>@item.Tour.NgayKhoiHanh</td>
                    <td>@item.Tour.NgayKetThuc</td>
                </tr>
            }
</table>
<a href="~/Admin/HomeAdmin/danhSachDatTour" class="btn btn-primary">Trở về</a>

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/ChiTietTour.cshtml
@model QuanLy_TourDuLich.Models.Tour

@{
    ViewBag.Title = "Chi tiết tour";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <h2>@Model.Name</h2>
            <p><strong>Mã tour:</strong> @Model.id</p>
            <p><strong>Loại tour:</strong> @Model.Loai_Tour.Name</p>
            <p><strong>Giá:</strong> @Model.Gia</p>
            <p><strong>Tiêu đề:</strong> @Model.TieuDe</p>
            <p><strong>Mô tả:</strong></p>
            <p>@Html.Raw(Model.MoTa)</p>
            <p><strong>Lịch trình:</strong></p>
            <p>@Html.Raw(Model.LichTrinh)</p>
            <p><strong>Điểm khởi hành:</strong> @Model.DiemKhoiHanh</p>
            <p><strong>Điểm đến:</strong> @Model.DiemDen</p>
            <p><strong>Ngày khởi hành:</strong> @String.Format("{0: dd/MM/yyyy}", Model.NgayKhoiHanh)</p>
            <p><strong>Ngày kết thúc:</strong> @String.Format("{0: dd/MM/yyyy}", Model.NgayKetThuc)</p>
            <p><strong>Số lượng còn:</strong> @Model.SoLuongCon</p>
            <p>Danh sách ảnh</p>
            @Html.Action("dsAnh", "HomeAdmin")
            <p>
                @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-primary" })
            </p>
        </div>
    </div>
</div>

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/Edit.cshtml
@model QuanLy_TourDuLich.Models.Tour
@using QuanLy_TourDuLich.Models

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";

}

<div class="container col-md-8">
    <h2>Thêm tour</h2>

    @using (Html.BeginForm("Edit", "HomeAdmin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(t => t.id)
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="col-md-2 form-label ">Loại tour</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Loai_Tour_id, (SelectList)ViewBag.LoaiTour, new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.Loai_Tour_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Tên tour</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Giá</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Tiêu đề</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Mô tả</label>
                <div class="col-md-10">
                    <textarea class="form-control" name="MoTa" id="inputMoTa">@Model.MoTa</textarea>
                    @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Lịch trình</label>
                <div class="col-md-10">
                    <textarea class="form-control" name="LichTrinh" id="inputLichTrinh">@Model.LichTrinh</textarea>

                    @Html.ValidationMessageFor(model => model.LichTrinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Điểm khởi hành</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiemKhoiHanh, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiemKhoiHanh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Điểm đến</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiemDen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiemDen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Ngày khởi hành</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayKhoiHanh, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.NgayKhoiHanh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Ngày kết thúc</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Số người</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoLuongCon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLuongCon, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Sửa" class="btn btn-danger" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section TourJS {
    <script>
        CKEDITOR.replace('inputMoTa')
        CKEDITOR.replace('inputLichTrinh')
    </script>
}

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/EditHinhAnhTour.cshtml
@model QuanLy_TourDuLich.Models.Tour
@using QuanLy_TourDuLich.Models;
@{
    ViewBag.Title = "Edit ảnh tour";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";

}

<b style="font-size:45px; color:black">Sửa hình ảnh tour</b>
@using (Html.BeginForm("EditHinhAnhTour", "HomeAdmin", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.HiddenFor(a=>a.id)
    <div class="form-group">
        <label class="control-label col-md-2">Hình ảnh hiện tại</label>
        <div class="col-md-10">
            @if (ViewBag.imgs != null && ViewBag.imgs.Count > 0)
            {
                foreach (var img in ViewBag.imgs as List<Image_Tour>)
                {
                    <div style="display:inline-block; position:relative; margin:5px;">
                        <img src="~/img/@img.Name" alt="@img.Name" style="max-width: 100px; max-height: 100px;" />
                        @using (Html.BeginForm("XoaHinhAnh", "HomeAdmin", FormMethod.Post))
                        {
                            @Html.Hidden("imageId", img.id)
                            @Html.Hidden("tourId", Model.id)
                            <button type="submit" class="btn btn-danger" style="position:absolute; top:0; right:0;">X</button>}
                    </div>}
            }
        </div>
    </div>

    <div class="form-group">
        <Label class="col-md-2">Images</Label>
        <div class="col-md-10">
            <input type="file" name="fileUpload" multiple />
            @ViewBag.Thongbao
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Sửa" class="btn btn-success" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/Index.cshtml
@model IEnumerable<QuanLy_TourDuLich.Models.Tour>

@{
    ViewBag.Title = "Quản lý tour";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<b style="font-size:45px; color:black">Quản lý Tour</b>

<p>
    @Html.ActionLink("Thêm Tour", "ThemMoiTour", null, new { @class = "btn btn-primary", @style = "font: bold; color:white; border-radius: 5px; font-weight: bold" })
</p>
<table class="table table-bordered">
    <tr>
        <th>
            <label>Loại tour</label>
        </th>
        <th>
            <label>Tên</label>
        </th>
        <th>
            <label>Giá</label>
        </th>
        <th>
            <label>Điểm khởi hành</label>
        </th>
        <th>
            <label>Điểm đến</label>
        </th>

        <th>
            <label>Ngày khởi hành</label>
        </th>
        <th>
            <label>Ngày kết thúc</label>
        </th>
        <th>
            <label>Số lượng còn</label>
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Loai_Tour.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @String.Format("{0:0,00}", item.Gia) VNĐ / người
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiemKhoiHanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiemDen)
            </td>
            <td>
                @String.Format("{0:dd/MM/yyyy}",item.NgayKhoiHanh)
            </td>
            <td>
                @String.Format("{0:dd/MM/yyyy}", item.NgayKetThuc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongCon)
            </td>

            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.id }) |
                @Html.ActionLink("Chi tiết", "ChiTietTour", new { id = item.id }) |
                <a onclick="xoa(@item.id)" href="#">Xóa</a> |
                <a href="~/Admin/HomeAdmin/ThemHinhAnhTour/@item.id">Thêm ảnh</a> |
                <a href="~/Admin/HomeAdmin/XoaHinhAnh/@item.id">Xóa ảnh</a>

            </td>
        </tr>
    }

</table>
<script>
    var xoa = function (id) {
        if (confirm("Bạn có chắc chắn muốn xóa không?")) {
            location.href = "XoaTour/" + id
        }
    }
</script>

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/ThemHinhAnhTour.cshtml
@model int

@{
    ViewBag.Title = "Thêm ảnh";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<b style="font-size:45px; color:black">
    Thêm hình ảnh vào tour</b>

    @using (Html.BeginForm("ThemHinhAnhTour", "HomeAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <input type="text" name="Tour_id" value="model" hidden />
            <div class="form-group">
                <Label class="col-md-2">Images</Label>
                <div class="col-md-10">
                    <input type="file" name="fileUpload" multiple />
                    @ViewBag.Thongbao
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/ThemMoiTour.cshtml
@model QuanLy_TourDuLich.Models.Tour
@using QuanLy_TourDuLich.Models
@{
    ViewBag.Title = "Thêm tour mới";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<div class="container col-md-8">
    <h2>Thêm tour</h2>

    @using (Html.BeginForm("ThemMoiTour", "HomeAdmin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class="col-md-2 form-label ">Loại tour</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Loai_Tour_id, (SelectList)ViewBag.LoaiTour, new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.Loai_Tour_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Tên tour</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Giá</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Tiêu đề</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Mô tả</label>
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })*@
                    <textarea class="form-control" name="MoTa" id="inputMoTa">@Model.MoTa</textarea>
                    @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Lịch trình</label>
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.LichTrinh, new { htmlAttributes = new { @class = "form-control" } })*@
                    <textarea class="form-control" name="LichTrinh" id="inputLichTrinh">@Model.LichTrinh</textarea>

                    @Html.ValidationMessageFor(model => model.LichTrinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Điểm khởi hành</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiemKhoiHanh, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiemKhoiHanh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Điểm đến</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiemDen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiemDen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Ngày khởi hành</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayKhoiHanh, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.NgayKhoiHanh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Ngày kết thúc</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 form-label">Số người</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoLuongCon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLuongCon, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-danger" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section TourJS {
    <script>
        CKEDITOR.replace('inputMoTa')
        CKEDITOR.replace('inputLichTrinh')
    </script>
}

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/XoaHinhAnh.cshtml
@model List<QuanLy_TourDuLich.Models.Image_Tour>
@{
    ViewBag.Title = "XoaHinhAnh";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";

}

<b style="font-size:45px; color:black">Ảnh hiện tại</b>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-3">
            <img src="~/img/@item.Name" alt="@item.Name" style="width: 95%;" />
            @using (Html.BeginForm("XoaHinhAnh", "HomeAdmin", FormMethod.Post))
            {
                @Html.Hidden("imageId", item.id)
                @Html.Hidden("tourId", item.Tour_id)
                <button type="submit" class="btn btn-danger">Xóa</button>
            }
        </div>
    }
</div>
<a href="~/Admin/HomeAdmin/Index" class="btn btn-info">Trở về</a>

QuanLy_TourDuLich/Areas/Admin/Views/HomeAdmin/dsAnh.cshtml
@model List<QuanLy_TourDuLich.Models.Image_Tour>

<ul>
    @foreach (var item in Model)
    {
    <li style="list-style:none">
        <img src="~/img/@item.Name"/>
    </li>
    }
</ul>