QuanLy_TourDuLich/Areas/Admin/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLy_TourDuLich.Models;
namespace QuanLy_TourDuLich.Areas.Admin.Controllers
{
    public class FeedbackController : Controller
    {
        CSDL_QLTourDataContext data = new CSDL_QLTourDataContext();
        public ActionResult Index()
        {
            var users = data.Feedbacks.ToList();
            return View(users);
        }
        public ActionResult Details(int id) 
        {
            var fb = data.Feedbacks.FirstOrDefault(t => t.id == id);
            return View(fb); 
        }

        public ActionResult Delete(int id)
        {
            data.Feedbacks.DeleteOnSubmit(data.Feedbacks.FirstOrDefault(t => t.id == id));
            data.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DanhGia(int? tourId)
        {
            var danhGias = data.DanhGias.AsQueryable();

            if (tourId.HasValue && tourId.Value > 0)
            {
                danhGias = danhGias.Where(dg => dg.Tour_id == tourId.Value);
            }

            var tours = data.Tours.ToList();
            ViewBag.Tours = new SelectList(tours, "Id", "Name", tourId);

            return View(danhGias.ToList());
        }
    }
}
    

QuanLy_TourDuLich/Areas/Admin/Views/Feedback/DanhGia.cshtml
@model IEnumerable<QuanLy_TourDuLich.Models.DanhGia>

@{
    ViewBag.Title = "Danh sách đánh giá";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<b style="font-size:45px; color:black">Đánh giá</b>

@using (Html.BeginForm("DanhGia", "Feedback", FormMethod.Get))
{
    <div class="form-group" style="display: flex; align-items: center;">
        <label for="TourId" style="margin-right: 10px;">Chọn Tour</label>

        <!-- Custom Dropdown Styling -->
        @Html.DropDownList("tourId", (SelectList)ViewBag.Tours, "Chọn tour", new { @class = "form-select", @style = "width: 300px; margin-right: 10px;" })
        <!-- Custom Button Styling -->
        <button type="submit" class="btn btn-success rounded-btn" style="font-size:17px">Lọc</button>
    </div>
}

@using (Html.BeginForm("DeleteSelected", "Feedback", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <table class="table">
        <thead>
            <tr>
                <th>Tên người dùng</th>
                <th>Tour</th>
                <th>Nội dung</th>
                <th>Đánh giá</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.KhachHang.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Tour.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.NoiDung)</td>
                    <td>
                        @{
                            switch (item.Vote)
                            {
                                case 1: <p>Tệ</p>; break;
                                case 2: <p>Tạm ổn</p>; break;
                                case 3: <p>Xuất sắc</p>; break;
                            }
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<style>



    .custom-dropdown {
        position: relative;
        appearance: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        background-color: #E9ECEF; 
        border: 1px solid #ced4da;
        padding: 8px 30px 8px 12px;
        font-size: 14px;
        line-height: 1.5;
        width: 100%;
        box-sizing: border-box;
        background-image: url('data:image/svg+xml;charset=US-ASCII,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 5"><path fill="%236c757d" d="M2 0L0 2h4z"/></svg>');
        background-repeat: no-repeat;
        background-position: right 10px center;
        background-size: 12px;
    }

        .custom-dropdown::-ms-expand {
            display: none;
        }
        .custom-dropdown:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }
</style>
<script>
    var xoa = function (id) {
        if (confirm("Bạn có chắc chắn muốn xóa không?")) {
            location.href = "FeedBack/Delete/" + id;
        }
    }
</script>

QuanLy_TourDuLich/Areas/Admin/Views/Feedback/Details.cshtml
@model QuanLy_TourDuLich.Models.Feedback

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}


<b style="font-size:45px; color:black">Chi tiết phản hồi</b>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tiêu đề 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDe)
        </dd>

        <dt>
            Nội dung
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>

        <dt>
            Ngày gửi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayPhanHoi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Quay lại", "Index")
</p>

QuanLy_TourDuLich/Areas/Admin/Views/Feedback/Index.cshtml
@model IEnumerable<QuanLy_TourDuLich.Models.Feedback>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<b style="font-size:45px; color:black">Phản hồi</b>

@using (Html.BeginForm("DeleteSelected", "Feedback", FormMethod.Post))
{
    @Html.AntiForgeryToken()



    <table class="table">
        <tr>
            <th>
                <label>Tiêu đề</label>
            </th>
            <th>
                <label>Ngày gửi</label>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TieuDe)
                </td>
                <td>
                    @String.Format("{0:dd/MM/yyyy}", item.NgayPhanHoi)
                </td>
                <td>
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.id }) | <a onclick="xoa(@item.id)" style="cursor:pointer">Xóa</a>
                </td>
            </tr>
        }
    </table>
}
<script>
    var xoa = function (id) {
        if (confirm("Bạn có chắc chắn muốn xóa không?")) {
            location.href = "FeedBack/Delete/" + id
        }
    }
</script>